[package]
name = "personal-webpage"
version = "0.1.0"
authors = ["Jerry Kurian <jkurian770@gmail.com>"]

[dependencies]
rocket = "*"
rocket_codegen = "*"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
